---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.demo.wecraft.tn
  resources:
  - sleepdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.wecraft.tn
  resources:
  - sleepdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - demo.demo.wecraft.tn
  resources:
  - sleepdeployments/status
  verbs:
  - get
  - patch
  - update
